{"toolset_name":"findings","tool_name":"fetch_finding_by_id","match_params":{"id":"5fa9728c-4dbe-4c10-81ce-48ecfa7c4ce1"}}
{
  "account_id": "debe17e5-0fe2-4c9c-9a7b-5dba04b83f89",
  "aggregation_key": "KubernetesWarningEvent",
  "annotations": {},
  "category": null,
  "cluster": "test_cluster",
  "creation_date": "2024-11-18T08:21:32.144684",
  "description": "Failed to pull image \\\"yourcompany/crw:latest\\\": failed to pull and unpack image \\\"docker.io/yourcompany/crw:latest\\\": failed to resolve reference \\\"docker.io/yourcompany/crw:latest\\\": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed",
  "ends_at": null,
  "evidence": [
    {
      "account_id": "debe17e5-0fe2-4c9c-9a7b-5dba04b83f89",
      "collection_timestamp": null,
      "creation_date": "2024-11-18T08:21:32.061455",
      "data": "[{\\\"type\\\": \\\"markdown\\\", \\\"data\\\": \\\"**Related Events**\\\"}, {\\\"type\\\": \\\"table\\\", \\\"data\\\": {\\\"headers\\\": [\\\"reason\\\", \\\"type\\\", \\\"time\\\", \\\"message\\\"], \\\"rows\\\": [[\\\"Scheduled\\\", \\\"Normal\\\", 1731918091183.75, \\\"Successfully assigned default/customer-relations-webapp-5d98ffcfd-tz4nc to ip-172-31-40-111.us-east-2.compute.internal\\\"], [\\\"Pulling\\\", \\\"Normal\\\", 1731918091000.0, \\\"Pulling image \\\\\\\"yourcompany/crw:latest\\\\\\\"\\\"], [\\\"Failed\\\", \\\"Warning\\\", 1731918091000.0, \\\"Failed to pull image \\\\\\\"yourcompany/crw:latest\\\\\\\": failed to pull and unpack image \\\\\\\"docker.io/yourcompany/crw:latest\\\\\\\": failed to resolve reference \\\\\\\"docker.io/yourcompany/crw:latest\\\\\\\": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed\\\"], [\\\"Failed\\\", \\\"Warning\\\", 1731918091000.0, \\\"Error: ErrImagePull\\\"]], \\\"column_renderers\\\": {\\\"time\\\": \\\"DATETIME\\\"}}, \\\"metadata\\\": {}}]",
      "enrichment_type": "k8s_events",
      "file_type": "structured_data",
      "id": "a2284f9e-11aa-4a1c-b72a-1985c1b1e145",
      "issue_id": "5fa9728c-4dbe-4c10-81ce-48ecfa7c4ce1",
      "title": "Related Events"
    }
  ],
  "failure": true,
  "finding_type": "issue",
  "fingerprint": "4396bc99d320067445030e77f6d2b9c9798a1835565f88e7c60fd31339e34486",
  "group_id": null,
  "id": "5fa9728c-4dbe-4c10-81ce-48ecfa7c4ce1",
  "labels": {},
  "priority": "DEBUG",
  "service_key": "default/Deployment/customer-relations-webapp",
  "service_kind": null,
  "source": "kubernetes_api_server",
  "starts_at": "2024-11-18T08:21:31.842217+00:00",
  "subject_name": "customer-relations-webapp-5d98ffcfd-tz4nc",
  "subject_namespace": "default",
  "subject_node": null,
  "subject_type": "pod",
  "title": "Failed Warning for Pod default/customer-relations-webapp-5d98ffcfd-tz4nc",
  "updated_at": "2024-11-18T08:21:32.119862+00:00",
  "video_links": []
}
